apiVersion: batch/v1
kind: Job
metadata:
  name: doctor
  namespace: demo
spec:
  template:
    spec:
      containers:
      - name: doctor
        env:
        - name: MONGODB_NAME
          value: "large"
        - name: MONGODB_NAMESPACE
          value: "demo"
        - name: MONGODB_URI
          value: "<URI>"
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        image: arnobkumarsaha/mongo-doctor
        imagePullPolicy: Always
      serviceAccountName: mongo-doctor
      restartPolicy: Never
  backoffLimit: 4