apiVersion: batch/v1
kind: Job
metadata:
  name: doctor
  namespace: demo
spec:
  template:
    spec:
      containers:
      - name: doctor
        env:
        - name: MONGODB_NAME
          value: "mm" # mm / test
        - name: MONGODB_NAMESPACE
          value: "demo"
#        - name: MONGODB_URI
#          value: "<>"
#        - name: SLOW_MS
#          value: "2"
        resources:
          requests:
            cpu: 1
            memory: 1Gi
        image: ghcr.io/arnobkumarsaha/mongo-doctor:v0.1.0_linux_amd64 # ghcr.io/kubedb/mongo-doctor:v0.1.0
        imagePullPolicy: Always
      serviceAccountName: mongo-doctor
      restartPolicy: Never
  backoffLimit: 4