apiVersion: apps.k8s.appscode.com/v1
kind: PlacementPolicy
metadata:
  name: hard-default
spec:
  nodeSpreadConstraint:
    maxSkew: 1
    whenUnsatisfiable: DoNotSchedule
  zoneSpreadConstraint:
    maxSkew: 1
    whenUnsatisfiable: DoNotSchedule
