apiVersion: v1
kind: ServiceAccount
metadata:
  name: mongo-doctor
  namespace: demo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mongo-doctor
rules:
  - apiGroups: ["kubedb.com"]
    resources: ["mongodbs"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create"]
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["*"]
  - apiGroups: [""]
    resources: ["pods/portforward"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: mongo-doctor
subjects:
  - kind: ServiceAccount
    name: mongo-doctor
    namespace: demo
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: mongo-doctor
  apiGroup: rbac.authorization.k8s.io